In [131]:
import plotly.express as px


# LINE CHART

In [132]:
#Creating an instance of a figure
fig=px.line(x=[1,2,3],y=[1,2,3])
print(fig)

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'mode': 'lines',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([1, 2, 3], dtype=int64),
              'xaxis': 'x',
              'y': array([1, 2, 3], dtype=int64),
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'y'}}}
})


In [133]:
fig

In [134]:
# Line chart using iris dataset
df= px.data.iris()
fig=px.line(df,x='species',y='petal_width',title='Iris')
fig

In [135]:
df=px.data.tips()
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [136]:
fig=px.line(df,x='day',y='total_bill',color='sex')

In [137]:
fig

In [138]:
# Using the line group argument
plot=px.line(df,x='time',y='tip',color='sex',line_group='day',line_dash='time')

In [139]:
plot

# BAR CHART

Syntax: plotly.express.bar(data_frame=None, x=None, y=None, color=None, facet_row=None, facet_col=None, facet_col_wrap=0, hover_name=None, hover_data=None, custom_data=None, text=None, error_x=None, error_x_minus=None, error_y=None, error_y_minus=None, animation_frame=None, animation_group=None, category_orders={}, labels={}, color_discrete_sequence=None, color_discrete_map={}, color_continuous_scale=None, range_color=None, color_continuous_midpoint=None, opacity=None, orientation=None, barmode=’relative’, log_x=False, log_y=False, range_x=None, range_y=None, title=None, template=None, width=None, height=None)

Parameters:

    Name                              Description
#data_frame	                   This argument needs to be passed for column names (and not keyword names) to be used. Array-like and dict are transformed internally to a pandas DataFrame. Optional: if missing, a DataFrame gets constructed under the hood using the other arguments.
#x	                           Either a name of a column in data_frame, or a pandas Series or array_like object. Values from this column or array_like are used to position marks along the x axis in cartesian coordinates. Either x or y can optionally be a list of column references or array_likes, in which case the data will be treated as if it were ‘wide’ rather than ‘long’.
#y	                           Either a name of a column in data_frame, or a pandas Series or array_like object. Values from this column or array_like are used to position marks along the y axis in cartesian coordinates. Either x or y can optionally be a list of column references or array_likes, in which case the data will be treated as if it were ‘wide’ rather than ‘long’.
#color	                       Either a name of a column in data_frame, or a pandas Series or array_like object. Values from this column or array_like are used to assign color to marks.

In [140]:
df=px.data.iris()
fig = px.bar(df, x="sepal_width", y="sepal_length") 
fig.show()

In [141]:
import numpy  as np
np.random.seed(1000)
x_rand=np.random.randint(1,1000,999)
y_rand=np.random.randint(1,1000,999)
fig=px.bar(x_rand,y=y_rand)
fig

# BAR CHART WITH LONG-FORM-DATASET

In [142]:
df=px.data.medals_long()
df

nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

In [143]:
fig=px.bar(df,x='nation',y='count',color='medal')
fig

# BAR CHART WITH WIDE-FORM-DATASET

In [144]:
df=px.data.medals_wide()
df

nation  gold  silver  bronze
0  South Korea    24      13      11
1        China    10      15       8
2       Canada     9      12      12

In [145]:
fig=px.bar(df,x='nation',y=['gold','silver','bronze']).show()

# BAR CHART SUBPLOTS USING facet_row,facet_col

In [146]:
df = px.data.iris()
#print(df)
 
fig = px.bar(df, x="sepal_width", y="sepal_length",
             color="species",facet_row="species")
fig.show()

# BAR PLOT OVERLAY MODE

In [147]:
df = px.data.iris()
# print(df)
 
fig = px.bar(df, x="sepal_width", y="sepal_length",
             color="species",barmode='overlay')
fig.show()

# HISTOGRAM

In [148]:
df=px.data.iris()
fig=px.histogram(df,x='sepal_width').show()

## Argument histnorm for different type of histogram
## histnorm='percent'
## histnorm='probability density'

In [149]:
df = px.data.tips()
  
fig = px.histogram(df, x="total_bill",
                   histnorm='probability density')
fig.show()

In [150]:
df = px.data.tips()
  
fig = px.histogram(df, x="total_bill",histnorm='percent',nbins=20)
                   
fig.show()

# STACKED VALUES IN HISTOGRAM USING COLOR

In [151]:
df = px.data.tips()
  
fig = px.histogram(df, x="total_bill",color="sex")
fig.show()

# DISTRIBUTION VISUALIZATION IN HISTOGRAM

In [152]:
# margin = rug, box , violin
fig = px.histogram(df, x="total_bill", marginal = 'violin')
fig.show()

# SCATTER PLOT

In [153]:
df = px.data.iris() 
fig = px.scatter(df, x="species", y="petal_width") 
  
# showing the plot
fig.show()

# BUBBLE PLOT USING SCATTER()

In [154]:
df = px.data.iris() 
fig = px.scatter(df, x="species", y="petal_width",size="petal_length",color="species") 
  
# showing the plot
fig.show()

# SCATTER PLOT SYMBOL PARAMETER

In [155]:
df = px.data.tips()
  
plot = px.scatter(df, x = 'day', 
                  y = 'total_bill',
                  color='sex', 
                  symbol = 'total_bill')
plot.show()

# PIE CHART

In [156]:
# using the tips dataset
df = px.data.tips() 
  
# plotting the pie chart
fig = px.pie(df, values="total_bill", names="day") 
  
# showing the plot
fig.show()

# PIE CHART WITH COLORS

In [157]:
# plotting the pie chart
fig = px.pie(df, values="total_bill", names="day",
             color_discrete_sequence=px.colors.sequential.Aggrnyl) 
  
# showing the plot
fig.show()

# BOX PLOT

In [158]:
# plotting the box chart
fig = px.box(df, x="day", y="total_bill") 
  
# showing the plot
fig.show()

# BOX PLOT TO SHOW ALL POINTS

In [159]:
# plotting the box chart
fig = px.box(df, x="day", y="total_bill",points="all") 
# DISPLAYS ALL POINTS
  
# showing the plot
fig.show()

# BOX PLOT TO SHOW OUTLIERS ONLY : DEFAULT

In [160]:
# plotting the box chart
fig = px.box(df, x="day", y="total_bill",points="outliers") 

  
# showing the plot
fig.show()

In [161]:
# plotting the box chart
fig = px.box(df, x="day", y="total_bill",points=False) 
# DISPLAYS 0 outliers
  
# showing the plot
fig.show()

# VIOLIN PLOT

In [162]:
# using the tips dataset
df = px.data.tips() 
  
# plotting the violin chart
fig = px.violin(df, x="day", y="total_bill")
  
# showing the plot
fig.show()

# GANTT CHART

In [163]:
import plotly.figure_factory as ff
  
df = [dict(Task="A", Start='2020-01-01', Finish='2009-02-02'),
      dict(Task="Job B", Start='2020-03-01', Finish='2020-11-11'),
      dict(Task="Job C", Start='2020-08-06', Finish='2020-09-21')]  
  
fig = ff.create_gantt(df)
fig.show()

# CONTOUR PLOTS

In [164]:
import plotly.graph_objects as go  
  
# Creating the X, Y value that will
# change the values of Z as a function
feature_x = np.arange(0, 50, 2) 
feature_y = np.arange(0, 50, 3) 
  
feature_x,feature_y

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48]),
 array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]))

In [165]:
# Creating 2-D grid of features 
[X, Y] = np.meshgrid(feature_x, feature_y) 
  
Z = np.cos(X / 2) + np.sin(Y / 4) 
  
Z

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
        -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
        -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
         0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901],
       [ 1.68163876,  1.22194107,  0.26549192, -0.30835374,  0.02799514,
         0.96530095,  1.64180905,  1.43554101,  0.53613873, -0.2294915 ,
        -0.15743277,  0.68606446,  1.52549272,  1.58908554,  0.81837598,
        -0.07804915, -0.27602072,  0.40647542,  1.34195547,  1.67034338,
         1.08972082,  0.1339095 , -0.31832207,  0.14880574,  1.10581777],
       [ 1.99749499,  1.53779729,  0.58134815,  0.00750249,  0.34385137,
         1.28115717,  1.95766527,  1.75139724,  0.85199495,  0.08636472,
         0.15842346,  1.00192068,  1.84134895,  1.90494177,  1.1342322 ,
         0.23780707,  0.03983551,  0.72233165,  1

In [166]:
# plotting the figure
fig = go.Figure(data=go.Contour(x = feature_x, y = feature_y, z = Z)) 
  
fig.show()

# HEATMAP

In [167]:
import plotly.graph_objects as go   
  
feature_x = np.arange(0, 50, 2) 
feature_y = np.arange(0, 50, 3) 
  
# Creating 2-D grid of features 
[X, Y] = np.meshgrid(feature_x, feature_y) 
  
Z = np.cos(X / 2) + np.sin(Y / 4) 
  
# plotting the figure
fig = go.Figure(data =
     go.Heatmap(x = feature_x, y = feature_y, z = Z,)) 
  
fig.show()

# ANNOTATED HEATMAPS

In [168]:
import plotly.figure_factory as ff
import numpy as np
  
feature_x = np.arange(0, 10, 2)
feature_y = np.arange(0, 10, 3)
  
# Creating 2-D grid of features
[X, Y] = np.meshgrid(feature_x, feature_y)
  
Z = np.cos(X / 2) + np.sin(Y / 4)
  
fig = ff.create_annotated_heatmap(Z)
fig.show()

# 3D LINE PLOT

In [169]:
import plotly.express as px 
  
# data to be pltted
df = px.data.tips() 
  
# plotting the figure
fig = px.line_3d(df, x="sex", y="day", 
                 z="time", color="sex") 
  
fig.show()

# 3D SCATTER PLOT

In [170]:
import plotly.express as px 
  
# Data to be plotted
df = px.data.iris() 
  
# Plotting the figure
fig = px.scatter_3d(df, x = 'sepal_width', 
                    y = 'sepal_length', 
                    z = 'petal_width', 
                    color = 'species') 
  
fig.show()